spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  application:
    name: configuration-service
  cloud:
    config:
      server:
   #     native:
    #      search-locations: classpath:/configs
        git:
          uri: https://github.com/maurogmiranda/configTrabajoFinal
          default-label: main

server:
  port: 8888
